```{r}
library(clp)
```

```{r}
n <- 20

x <- rexp(n)
y <- rexp(n)

B <- 10000
```

# One-sample Mean

```{r}
par(mfrow = c(1, 2))

conf.boot <- t_test.boot.conf(x, B = B, plot = TRUE)
conf.para <- t.conf(x)

xlim <- conf.para$qconf(c(0.001, 0.999))

par(mfrow = c(1, 1))
curve(conf.boot$dconf(x), xlim = xlim, n = 2001, col = 'red')
curve(conf.para$dconf(x), n = 2001, add = TRUE, col = 'blue')

par(mfrow = c(1, 1))
curve(conf.boot$cconf(x), xlim = xlim, n = 2001, col = 'red')
curve(conf.para$cconf(x), n = 2001, add = TRUE, col = 'blue')
```

```{r}
par(mfrow = c(1, 1))
curve(conf.boot$scurve(x), xlim = conf.para$qconf(c(0.001, 0.999)), n = 2001, col = 'red')
curve(conf.para$scurve(x), n = 2001, add = TRUE, col = 'blue')
```

# Two-sample Mean

```{r}
par(mfrow = c(1, 2))
conf.boot <- t_test.boot.conf(x, y, B = B, plot = TRUE)

conf.para <- t.conf(x, y)

xlim <- conf.para$qconf(c(0.001, 0.999))

par(mfrow = c(1, 1))
curve(conf.boot$dconf(x), xlim = xlim, n = 2001, col = 'red')
curve(conf.para$dconf(x), n = 2001, add = TRUE, col = 'blue')

par(mfrow = c(1, 1))
curve(conf.boot$cconf(x), xlim = xlim, n = 2001, col = 'red')
curve(conf.para$cconf(x), n = 2001, add = TRUE, col = 'blue')
```

```{r}
par(mfrow = c(1, 1))
curve(conf.boot$scurve(x), xlim = conf.para$qconf(c(0.001, 0.999)), n = 2001, col = 'red')
curve(conf.para$scurve(x), n = 2001, add = TRUE, col = 'blue')
```

Need to handle P-values for bootstrap that yield NAs.

```{r}
conf.boot$pcurve(0)
conf.para$pcurve(0)

conf.boot$pcurve(5)
conf.para$pcurve(5)
```

# Bootstrap for Coefficients of Linear Model

```{r}
data(fat)

formula <- body.fat ~ age + weight + height

mod <- lm(formula, data = fat)

beta.conf <- lm.beta.conf(mod)

beta.boot.conf <- lm.beta.boot.conf(formula, data = fat, B = 2000)

for (nam in names(beta.boot.conf)){
  xlim <- beta.boot.conf[[nam]]$qconf(c(0.001, 0.999))
  curve(beta.conf[[nam]]$cconf(x), xlim = xlim, col = 'red', n = 2000, xlab = nam)
  curve(beta.boot.conf[[nam]]$cconf(x), add = TRUE, col = 'blue', n = 2000)
}

for (nam in names(beta.boot.conf)){
  xlim <- beta.boot.conf[[nam]]$qconf(c(0.001, 0.999))
  curve(beta.conf[[nam]]$dconf(x), xlim = xlim, col = 'red', n = 2000, xlab = nam)
  curve(beta.boot.conf[[nam]]$dconf(x), add = TRUE, col = 'blue', n = 2000)
}
```

# Bootstrap for Coefficients of Linear Model with Multiple Corrections via Beran

```{r}
data(fat)

formula <- body.fat ~ age + weight + height

statistic <- function(data, id = 1:nrow(data)){
  mod <- lm(formula, data = data[id, ])
  
  return(coef(mod))
}

bc <- bcaboot(fat, statistic, B = 2000)

beta.conf.simul <- bootstrap.beran.conf(bc, which = 2:4)
beta.boot.conf <- conffuns.from.percboot(bc)

for (nam in names(beta.conf.simul)){
  xlim <- beta.conf.simul[[nam]]$qconf(c(0.001, 0.999))
  curve(beta.conf.simul[[nam]]$cconf(x), xlim = xlim, col = 'red', n = 2000, xlab = nam)
  curve(beta.boot.conf[[nam]]$cconf(x), add = TRUE, col = 'blue', n = 2000)
}
```
