---
title: Confidence Curves for Parameters of a GLM
author: David Darmon
date: 010720
output: html_document
---

```{r, message = FALSE}
library(clp)
```

# Example 2.4 on Page 38 of CLP

```{r}
data(lbw)

mod <- glm(low ~ weight + age + black + other + smoker, data = lbw, family = binomial)
```

# Demo all of the curves

```{r}
conf.out <- glm.beta.conf(mod)

alpha = 0.05

ci.out <- confint(mod, level = 1 - alpha)

alpha.lower <- 0.0001

n.plot <- 401

for (var.name in names(coef(mod))){
  par(mfrow = c(2, 2))
  
  Qn <- conf.out[[var.name]]$qconf
  
  xlim <- c(Qn(alpha.lower/2), Qn(1-alpha.lower/2))
  
  curve(conf.out[[var.name]]$pconf(x), xlim = xlim,
        n = n.plot, xlab = var.name, ylab = 'Confidence Dist.')
  
  curve(conf.out[[var.name]]$cconf(x), xlim = xlim, n = n.plot, 
        xlab = var.name, ylab = 'Confidence Curve')
  abline(v = ci.out[var.name, ], h = 1-alpha, lty = 3)
  abline(v = c(conf.out[[var.name]]$qconf(alpha/2), conf.out[[var.name]]$qconf(1-alpha/2)), lty = 4, col = 'red')
  
  #curve(conf.out[[var.name]]$pcurve(x), xlim = xlim, n = n.plot)
  
  curve(conf.out[[var.name]]$dconf(x), xlim = xlim, n = n.plot, 
        xlab = var.name, ylab = 'Confidence Dens.')
  curve(conf.out[[var.name]]$scurve(x), xlim = xlim, n = n.plot, 
        xlab = var.name, ylab = 'S-curve')
}
```
# S-curve as evidence-against-null-in-coin-flips

```{r}
conf.out$weight$scurve(0)
conf.out$smoker$scurve(0)
```

# Still need to fix:

```{r}
# Need a way to handle "out of bound" queries that give NAs

conf.out$weight$cconf(3)

conf.out$weight$qconf(1e-9)
```
