```{r}
library(clp)

data(fat)
```


# Data Set for Body Fat Prediction

http://lib.stat.cmu.edu/datasets/bodyfat

```{r}
mod.lm <- lm(body.fat ~ age + weight + height, data = fat)
mod.glm <- glm(body.fat ~ age + weight + height, data = fat, family = gaussian)

par(mfrow = c(2, 2))
plot(mod.lm)

```

# Confidence Curve for Coefficients

```{r}
conf.out <- lm.beta.conf(mod.lm)

alpha = 0.05

ci.out <- confint(mod.lm, level = 1 - alpha)

alpha.lower <- 0.0001

n.plot <- 401

for (var.name in names(coef(mod.lm))){
  par(mfrow = c(2, 2))
  
  cur.conf <- conf.out[[var.name]]
  
  xlim <- cur.conf$qconf(c(alpha.lower/2, 1-alpha.lower/2))
  
  curve(cur.conf$pconf(x), xlim = xlim,
        n = n.plot, xlab = var.name, ylab = 'Confidence Dist.')
  
  curve(cur.conf$cconf(x), xlim = xlim, n = n.plot, 
        xlab = var.name, ylab = 'Confidence Curve')
  abline(v = ci.out[var.name, ], h = 1-alpha, lty = 3)
  abline(v = cur.conf$qconf(c(alpha/2, 1 - alpha/2)), lty = 4, col = 'red')
  
  curve(cur.conf$dconf(x), xlim = xlim, n = n.plot, 
        xlab = var.name, ylab = 'Confidence Dens.')
  curve(cur.conf$scurve(x), xlim = xlim, n = n.plot, 
        xlab = var.name, ylab = 'S-curve')
}
```
```{r}
plot.dconf(conf.out$age)
plot.cconf(conf.out$age)

plot.dconf(conf.out$height)
plot.cconf(conf.out$height)
```


# Confidence curve for the expected BFP of a 170lb, 6ft, 20-year old male

Need to make optimization for glm.lincom.conf.disp() more robust.

```{r}
x <- c(1,    # Intercept
       20,   # 20 years old
       170,  # 170 lbs
       6*12) # 72 inches (6 feet)

conf.out.lm <- lm.lincom.conf(mod.lm, x)

conf.out.glm <- glm.lincom.conf.disp(mod.glm, x)
```

## Compare exact cc from Gaussian noise to GLM cc

```{r}
curve(conf.out.lm$cconf(x), from = 9, to = 14, n = 2001, col = 'blue')
curve(conf.out.glm$cconf(x), from = 9, to = 14, n = 2001, col = 'red', lty = 3, add = TRUE)
```

```{r}
resp <- seq(9, 14, length.out = 2000)

plot(resp, conf.out.lm$cc(resp) - conf.out.glm$cc(resp))

curve(0.01*(conf.out.lm$cc(x)-1), add = TRUE)
```

